on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      PATCH_VERSION_OFFSET: -12
      MAJOR_VERSION: 0
      MINOR_VERSION: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: "Build APK"
        run: |
          flutter clean
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs  
          flutter build apk --split-per-abi
      - name: "Retrieve patch version"
        run: |
          echo "PATCH_VERSION=$((${{ github.run_number }} + ${{ env.PATCH_VERSION_OFFSET }}))" >> $GITHUB_ENV
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}
          token: ${{ secrets.TOKEN }}
