on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: "Build APK"
        run: |
          flutter clean
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs  
          flutter build apk --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
# Push to master, main, develop
# pull request on main master
